### ISSUE TITLE
vagrant上面运行rake --trace db:schema:load报错

### ISSUE THREAD

**Issue by yangwenmai** [chloerei/campo#23]
vagrant上面运行rake --trace db:schema:load报错

```
vagrant@precise64:/vagrant$ rake --trace db:schema:load
rake aborted!
no such file to load -- bundler/setup
/vagrant/config/boot.rb:4:in `require'
/vagrant/config/boot.rb:4
/vagrant/config/application.rb:1:in `require'
/vagrant/config/application.rb:1
/vagrant/Rakefile:4:in `require'
/vagrant/Rakefile:4
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:501:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:82:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:81:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:65:in `run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:63:in `run'
/usr/bin/rake:27
```

**Comment by chloerei** [comment]
换 `rake db:setup` 看看

**Comment by yangwenmai** [comment]
运行rake db:setup时，报错找不到rake,我装rake又报错无法安装
```Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  libruby1.8 ruby ruby1.8 unzip zip
Suggested packages:
  ruby1.8-examples rdoc1.8 ri1.8
The following NEW packages will be installed:
  libruby1.8 rake ruby ruby1.8 unzip zip
0 upgraded, 6 newly installed, 0 to remove and 36 not upgraded.
Need to get 1554kB/2241kB of archives.
After this operation, 8765kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Err http://us.archive.ubuntu.com/ubuntu/ lucid-updates/main libruby1.8 1.8.7.249-2ubuntu0.1
  404  Not Found [IP: 91.189.91.13 80]
Err http://security.ubuntu.com/ubuntu/ lucid-security/main libruby1.8 1.8.7.249-2ubuntu0.1
  404  Not Found [IP: 91.189.92.200 80]
Err http://security.ubuntu.com/ubuntu/ lucid-security/main ruby1.8 1.8.7.249-2ubuntu0.1
  404  Not Found [IP: 91.189.92.200 80]
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/r/ruby1.8/libruby1.8_1.8.7.249-2ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.92.200 80]
Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/r/ruby1.8/ruby1.8_1.8.7.249-2ubuntu0.1_amd64.deb  404  Not Found [IP: 91.189.92.200 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

``````
然后我使用```sudo apt-get update```
再次运行，还是报上面的错误。
``````

**Comment by chloerei** [comment]
`script/setup.sh` 这个一键安装脚本运行了没？

**Comment by yangwenmai** [comment]
运行过，不过我又重新运行了，但是好像每次都要再重新去执行里面的下载安装？现在还在下载中。

**Comment by chloerei** [comment]
日志显示至少 Ruby 没有安装，还用的是系统自带的 Ruby。项目脚本是通过 rvm 安装 ruby 2.1.1。

再看看 `script/setup.sh` 过程有什么错误。

**Comment by yangwenmai** [comment]
运行setup.sh会报错：

```
Using /home/vagrant/.rvm/gems/ruby-2.1.1
cp: cannot create regular file `config/database.yml': Operation not permitted
cp: cannot create regular file `config/secrets.yml': Operation not permitted
cp: cannot create regular file `config/config.yml': Operation not permitted
Fetching source index from https://rubygems.org/
Fetching git://github.com/chloerei/turbolinks.git
You need to install git to be able to use gems from git repositories. For
help installing git, please refer to GitHub's tutorial at
https://help.github.com/articles/set-up-git
Could not find rake-10.2.2 in any of the sources
Run `bundle install` to install missing gems.
/home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.2.2 in any of the sources (Bundler::GemNotFound)
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `map!'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/spec_set.rb:85:in `materialize'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/definition.rb:133:in `specs'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/definition.rb:178:in `specs_for'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/definition.rb:167:in `requested_specs'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/environment.rb:18:in `requested_specs'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/runtime.rb:13:in `setup'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler.rb:119:in `setup'
    from /home/vagrant/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.5.3/lib/bundler/setup.rb:17:in `<top (required)>'
    from /home/vagrant/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/vagrant/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
 System start/stop links for /etc/init.d/resque already exist.
cp: cannot create regular file `/etc/nginx/sites-available/campo': No such file or directory
sed: can't read /etc/nginx/sites-available/campo: No such file or directory
ln: creating symbolic link `/etc/nginx/sites-enabled': No such file or directory
rm: cannot remove `/etc/nginx/sites-enabled/default': No such file or directory
sed: can't read /etc/nginx/nginx.conf: No such file or directory
sed: can't read /etc/nginx/nginx.conf: No such file or directory
nginx: unrecognized service
```

**Comment by chloerei** [comment]
git 没有安装。配合前面的日志，可能 `apt-get update` 的时候失败了，后面的安装有很多都没有完成。手工 `apt-get update` 然后 `apt-get install git` 看看。

**Comment by yangwenmai** [comment]
安装git报错

```
vagrant@lucid64:/vagrant/git/campo$ sudo apt-get install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package git has no installation candidate
```

**Comment by chloerei** [comment]
apt-get update 了没？再试试 install git-core

**Comment by yangwenmai** [comment]
还是不行，执行setup.sh后，还是无法成功。

```
The following information may help to resolve the situation:

The following packages have unmet dependencies:
  nginx-extras: Depends: perl (>= 5.14.2-6ubuntu2.4) but 5.10.1-8ubuntu2.1 is to be installed
                Depends: perlapi-5.14.2 but it is not installable
                Depends: libc6 (>= 2.14) but 2.11.1-0ubuntu7.10 is to be installed
                Depends: libgeoip1 (>= 1.4.8+dfsg) but 1.4.6.dfsg-17 is to be installed
                Depends: libpcre3 (>= 8.10) but 7.8-3build1 is to be installed
                Depends: libperl5.14 (>= 5.14.2) but it is not installable
                Depends: libssl1.0.0 (>= 1.0.1) but it is not installable
                Depends: libstdc++6 (>= 4.6) but 4.4.3-4ubuntu5.1 is to be installed
                Recommends: passenger (< 4.0.42) but 1:4.0.41-1~precise1 is to be installed
  passenger: Depends: libc6 (>= 2.14) but 2.11.1-0ubuntu7.10 is to be installed
             Depends: libev4 (>= 1:4.04) but it is not installable
             Depends: libpcre3 (>= 8.10) but 7.8-3build1 is to be installed
             Depends: ruby-rack but it is not installable
E: Broken packages
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 73 not upgraded.
Downloading https://github.com/wayneeseguin/rvm/archive/stable.tar.gz

Upgrading the RVM installation in /home/vagrant/.rvm/
cp: cannot stat `/home/vagrant/.rvm/src/rvm/bin/rake': No such file or directory
cp: cannot stat `/home/vagrant/.rvm/src/rvm/bin/bundle': No such file or directory
    RVM PATH line found in /home/vagrant/.profile /home/vagrant/.bashrc /home/vagrant/.zshrc.
    RVM sourcing line found in /home/vagrant/.bash_profile /home/vagrant/.zlogin.
Upgrade of RVM in /home/vagrant/.rvm/ is complete.

# vagrant,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

Already installed ruby-2.1.1.
To reinstall use:

    rvm reinstall ruby-2.1.1

Using /home/vagrant/.rvm/gems/ruby-2.1.1
cp: cannot create regular file `config/database.yml': Operation not permitted
cp: cannot create regular file `config/secrets.yml': Operation not permitted
cp: cannot create regular file `config/config.yml': Operation not permitted
Fetching source index from https://rubygems.org/
```

**Comment by chloerei** [comment]
问题是 `apt-get update` 成功了没啊？

**Comment by yangwenmai** [comment]
成功

```
vagrant@lucid64:/vagrant/git/campo$ sudo apt-get update
Hit http://us.archive.ubuntu.com lucid Release.gpg                          
Get:1 http://us.archive.ubuntu.com lucid-updates Release.gpg [198B]         
Hit http://packages.elasticsearch.org stable Release.gpg                    
Hit http://us.archive.ubuntu.com lucid Release                              
Hit http://packages.elasticsearch.org stable Release                        
Get:2 http://us.archive.ubuntu.com lucid-updates Release [58.3kB]           
Hit https://oss-binaries.phusionpassenger.com precise Release.gpg           
Hit http://us.archive.ubuntu.com lucid/main Packages                        
Hit http://us.archive.ubuntu.com lucid/restricted Packages                  
Hit http://us.archive.ubuntu.com lucid/main Sources                         
Hit http://us.archive.ubuntu.com lucid/restricted Sources                   
Hit http://us.archive.ubuntu.com lucid/universe Packages                    
Hit http://us.archive.ubuntu.com lucid/universe Sources                     
Hit http://us.archive.ubuntu.com lucid/multiverse Packages                  
Hit http://us.archive.ubuntu.com lucid/multiverse Sources                   
Hit https://oss-binaries.phusionpassenger.com precise Release               
Get:3 http://us.archive.ubuntu.com lucid-updates/main Packages [740kB]      
Ign https://oss-binaries.phusionpassenger.com precise/main Packages         
Ign http://packages.elasticsearch.org stable/main Packages                  
Ign https://oss-binaries.phusionpassenger.com precise/main Packages         
Ign http://packages.elasticsearch.org stable/main Packages                  
Get:4 http://security.ubuntu.com lucid-security Release.gpg [198B]          
Get:5 http://security.ubuntu.com lucid-security Release [57.3kB]            
Hit https://oss-binaries.phusionpassenger.com precise/main Packages         
Get:6 http://security.ubuntu.com lucid-security/main Packages [551kB]       
Get:7 http://us.archive.ubuntu.com lucid-updates/restricted Packages [4624B]
Get:8 http://us.archive.ubuntu.com lucid-updates/main Sources [335kB]       
Get:9 http://security.ubuntu.com lucid-security/restricted Packages [2829B] 
Get:10 http://security.ubuntu.com lucid-security/main Sources [242kB]       
Get:11 http://us.archive.ubuntu.com lucid-updates/restricted Sources [2196B]
Get:12 http://us.archive.ubuntu.com lucid-updates/universe Packages [345kB] 
Get:13 http://us.archive.ubuntu.com lucid-updates/universe Sources [110kB]  
Get:14 http://us.archive.ubuntu.com lucid-updates/multiverse Packages [11.5kB]
Get:15 http://us.archive.ubuntu.com lucid-updates/multiverse Sources [5817B]
Get:16 http://security.ubuntu.com lucid-security/restricted Sources [1267B] 
Get:17 http://security.ubuntu.com lucid-security/universe Packages [197kB]  
Hit http://packages.elasticsearch.org stable/main Packages                  
Get:18 http://security.ubuntu.com lucid-security/universe Sources [46.7kB]  
Get:19 http://security.ubuntu.com lucid-security/multiverse Packages [5373B]
Get:20 http://security.ubuntu.com lucid-security/multiverse Sources [2347B] 
Fetched 2718kB in 22s (121kB/s)                                             
Reading package lists... Done
vagrant@lucid64:/vagrant/git/campo$ rake db:setup
(in /vagrant/git/campo)
rake aborted!
no such file to load -- bundler/setup
/vagrant/git/campo/Rakefile:4:in `require'
(See full trace by running task with --trace)
```

**Comment by chloerei** [comment]
这个源不对，显示的是 lucid（10.04），Vagrant 定义的是 precise（12.04），有做过什么更改吗？

**Comment by yangwenmai** [comment]
我下载安装vagrant之后只配置过go环境，其他未做更改

**Comment by chloerei** [comment]
现在的 setup.sh 是专为 12.04 写的，所以你要新开一个虚拟机。先在 host 机把源码 clone 下来，然后在项目文件夹里面 `vagrant up`。

**Comment by yangwenmai** [comment]
我按照此方式执行setup.sh后，报错

```
Using /home/vagrant/.rvm/gems/ruby-2.1.1
cp: cannot create regular file `config/database.yml': Permission denied
cp: cannot create regular file `config/secrets.yml': Permission denied
cp: cannot create regular file `config/config.yml': Permission denied
```

```
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
PG::InvalidParameterValue: ERROR:  encoding UTF8 does not match locale en_US
DETAIL:  The chosen LC_CTYPE setting requires encoding LATIN1.
: CREATE DATABASE "campo_development" ENCODING = 'unicode'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
...
/home/vagrant/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "username"=>nil, "password"=>nil, "database"=>"campo_development"}
PG::InvalidParameterValue: ERROR:  encoding UTF8 does not match locale en_US
DETAIL:  The chosen LC_CTYPE setting requires encoding LATIN1.
: CREATE DATABASE "campo_test" ENCODING = 'unicode'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:373:in `block in log'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activesupport-4.1.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/abstract_adapter.rb:367:in `log'
...
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "username"=>nil, "password"=>nil, "database"=>"campo_test"}
PG::InvalidParameterValue: ERROR:  encoding UTF8 does not match locale en_US
DETAIL:  The chosen LC_CTYPE setting requires encoding LATIN1.
: CREATE DATABASE "campo_production" ENCODING = 'unicode'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
...
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "username"=>nil, "password"=>nil, "database"=>"campo_production"}
 System start/stop links for /etc/init.d/resque already exist.
ln: failed to create symbolic link `/etc/nginx/sites-enabled/campo': File exists
rm: cannot remove `/etc/nginx/sites-enabled/default': No such file or directory
 * Restarting nginx nginx                                             [ OK ] 
vagrant@precise64:/vagrant$ 
```

我尝试rake db:create或者rake db:setup都会报错。
错误信息：

```
vagrant@precise64:/vagrant$ rake db:create
PG::InvalidParameterValue: ERROR:  encoding UTF8 does not match locale en_US
DETAIL:  The chosen LC_CTYPE setting requires encoding LATIN1.
: CREATE DATABASE "campo_development" ENCODING = 'unicode'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
```

**Comment by chloerei** [comment]
重装一下 postgresql

```
sudo apt-get purge postgresql libpq-dev
sudo apt-get autoremove
sudo rm -r /etc/postgresql/
sudo rm -r /etc/postgresql-common/
sudo rm -r /var/lib/postgresql/
sudo userdel -r postgres
sudo groupdel postgres

sudo update-locale LC_ALL="en_US.utf8"
export LC_ALL=en_US.UTF-8
sudo apt-get install postgresql libpq-dev
```

**Comment by yangwenmai** [comment]
```
vagrant@precise64:/vagrant$ sudo rm -r /etc/postgresql/
vagrant@precise64:/vagrant$ sudo rm -r /etc/postgresql-common/
vagrant@precise64:/vagrant$ sudo rm -r /var/lib/postgresql/
vagrant@precise64:/vagrant$ sudo userdel -r postgres
userdel: postgres home directory (/var/lib/postgresql) not found
vagrant@precise64:/vagrant$ sudo userdel -r postgres
userdel: user 'postgres' does not exist
vagrant@precise64:/vagrant$ sudo groupdel postgres
groupdel: group 'postgres' does not exist
vagrant@precise64:/vagrant$ sudo update-locale LC_ALL='en_US.utf8'
vagrant@precise64:/vagrant$ export LC_ALL=en_US.UTF-8
vagrant@precise64:/vagrant$ sudo apt-get install postgresql libpq-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  comerr-dev krb5-multidev libgssrpc4 libkadm5clnt-mit8 libkadm5srv-mit8
  libkdb5-6 libkrb5-dev libpq5 postgresql-9.1 postgresql-client-9.1
  postgresql-client-common postgresql-common
Suggested packages:
  doc-base krb5-doc krb5-user postgresql-doc-9.1 oidentd ident-server
  locales-all
The following NEW packages will be installed:
  comerr-dev krb5-multidev libgssrpc4 libkadm5clnt-mit8 libkadm5srv-mit8
  libkdb5-6 libkrb5-dev libpq-dev libpq5 postgresql postgresql-9.1
  postgresql-client-9.1 postgresql-client-common postgresql-common
0 upgraded, 14 newly installed, 0 to remove and 145 not upgraded.
Need to get 0 B/6,067 kB of archives.
After this operation, 17.0 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Preconfiguring packages ...
Selecting previously unselected package libgssrpc4.
(Reading database ... 59325 files and directories currently installed.)
Unpacking libgssrpc4 (from .../libgssrpc4_1.10+dfsg~beta1-2ubuntu0.3_amd64.deb) ...
Selecting previously unselected package libkadm5clnt-mit8.
Unpacking libkadm5clnt-mit8 (from .../libkadm5clnt-mit8_1.10+dfsg~beta1-2ubuntu0.3_amd64.deb) ...
Selecting previously unselected package libkdb5-6.
Unpacking libkdb5-6 (from .../libkdb5-6_1.10+dfsg~beta1-2ubuntu0.3_amd64.deb) ...
Selecting previously unselected package libkadm5srv-mit8.
Unpacking libkadm5srv-mit8 (from .../libkadm5srv-mit8_1.10+dfsg~beta1-2ubuntu0.3_amd64.deb) ...
Selecting previously unselected package comerr-dev.
Unpacking comerr-dev (from .../comerr-dev_2.1-1.42-1ubuntu2_amd64.deb) ...
Selecting previously unselected package krb5-multidev.
Unpacking krb5-multidev (from .../krb5-multidev_1.10+dfsg~beta1-2ubuntu0.3_amd64.deb) ...
Selecting previously unselected package libpq5.
Unpacking libpq5 (from .../libpq5_9.1.13-0ubuntu0.12.04_amd64.deb) ...
Selecting previously unselected package libkrb5-dev.
Unpacking libkrb5-dev (from .../libkrb5-dev_1.10+dfsg~beta1-2ubuntu0.3_amd64.deb) ...
Selecting previously unselected package libpq-dev.
Unpacking libpq-dev (from .../libpq-dev_9.1.13-0ubuntu0.12.04_amd64.deb) ...
Selecting previously unselected package postgresql-client-common.
Unpacking postgresql-client-common (from .../postgresql-client-common_129ubuntu1_all.deb) ...
Selecting previously unselected package postgresql-client-9.1.
Unpacking postgresql-client-9.1 (from .../postgresql-client-9.1_9.1.13-0ubuntu0.12.04_amd64.deb) ...
Selecting previously unselected package postgresql-common.
Unpacking postgresql-common (from .../postgresql-common_129ubuntu1_all.deb) ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Selecting previously unselected package postgresql-9.1.
Unpacking postgresql-9.1 (from .../postgresql-9.1_9.1.13-0ubuntu0.12.04_amd64.deb) ...
Selecting previously unselected package postgresql.
Unpacking postgresql (from .../postgresql_9.1+129ubuntu1_all.deb) ...
Processing triggers for install-info ...
Processing triggers for man-db ...
Processing triggers for ureadahead ...
Setting up libgssrpc4 (1.10+dfsg~beta1-2ubuntu0.3) ...
Setting up libkadm5clnt-mit8 (1.10+dfsg~beta1-2ubuntu0.3) ...
Setting up libkdb5-6 (1.10+dfsg~beta1-2ubuntu0.3) ...
Setting up libkadm5srv-mit8 (1.10+dfsg~beta1-2ubuntu0.3) ...
Setting up comerr-dev (2.1-1.42-1ubuntu2) ...
Setting up krb5-multidev (1.10+dfsg~beta1-2ubuntu0.3) ...
Setting up libpq5 (9.1.13-0ubuntu0.12.04) ...
Setting up libkrb5-dev (1.10+dfsg~beta1-2ubuntu0.3) ...
Setting up libpq-dev (9.1.13-0ubuntu0.12.04) ...
Setting up postgresql-client-common (129ubuntu1) ...
Setting up postgresql-client-9.1 (9.1.13-0ubuntu0.12.04) ...
update-alternatives: using /usr/share/postgresql/9.1/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode.
Setting up postgresql-common (129ubuntu1) ...
Setting up postgresql-9.1 (9.1.13-0ubuntu0.12.04) ...
update-alternatives: using /usr/share/postgresql/9.1/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode.
Setting up postgresql (9.1+129ubuntu1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
vagrant@precise64:/vagrant$ rake db:schema:load
/vagrant/db/schema.rb doesn't exist yet. Run `rake db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /vagrant/config/application.rb to limit the frameworks that will be loaded.
vagrant@precise64:/vagrant$ rake db:setup
could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `initialize'
```

**Comment by chloerei** [comment]
`rake db:create:all`

**Comment by yangwenmai** [comment]
还是报错。

```
vagrant@precise64:/vagrant$ rake db:create:all
could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
/home/vagrant/.rvm/gems/ruby-2.1.1/gems/activerecord-4.1.0/lib/active_record/connection_adapters/postgresql_adapter.rb:881:in `initialize'
...
home/vagrant/.rvm/gems/ruby-2.1.1/bin/rake:23:in `load'
/home/vagrant/.rvm/gems/ruby-2.1.1/bin/rake:23:in `<main>'
/home/vagrant/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/vagrant/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "username"=>nil, "password"=>nil, "database"=>"campo_production"}
vagrant@precise64:/vagrant$
```

**Comment by chloerei** [comment]
```
sudo service postgresql start
sudo su postgres -c "createuser -d -R -S vagrant"
```

**Comment by yangwenmai** [comment]
```
vagrant@precise64:/vagrant$ sudo service postgresql start
vagrant@precise64:/vagrant$ sudo su postgres -c "createuser -d -R -S vagrant"createuser: could not connect to database postgres: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
vagrant@precise64:/vagrant$
```

**Comment by chloerei** [comment]
悲剧，太乱了。

```
vagrant destroy
```

删掉虚拟机，回到 host 用 git 回滚到上一个 commit

```
git reset --hard 8d6dc916d864aa6bcafa03062a8499b978096185
```

然后再

```
vagrant up
```

这个应该没问题了，问题是最后一个 commit 引入的。

**Comment by yangwenmai** [comment]
我按照之前的办法重新执行了一遍，
执行setup.sh后没发现错误,只是在fetching rubygem.org时很卡，然后我重新又执行了一次setup.sh。
有这个错误提示

```
Upgrading the RVM installation in /home/vagrant/.rvm/
cp: cannot stat `/home/vagrant/.rvm/src/rvm/bin/rake': No such file or directory
cp: cannot stat `/home/vagrant/.rvm/src/rvm/bin/bundle': No such file or directory
    RVM PATH line found in /home/vagrant/.profile /home/vagrant/.bashrc /home/vagrant/.zshrc.
    RVM sourcing line found in /home/vagrant/.bash_profile /home/vagrant/.zlogin.
Upgrade of RVM in /home/vagrant/.rvm/ is complete.
```

```
rake --trace db:schema:load
```

报错，然后我安装sudo apt-get update,然后安装了git-core,rake，执行

```
rake --trace db:create:all
```

还是报错哦。

```vagrant@precise64:/vagrant$ rake --trace db:create:all
rake aborted!
no such file to load -- bundler/setup
/vagrant/config/boot.rb:4:in`require'
/vagrant/config/boot.rb:4
/vagrant/config/application.rb:1:in `require'
/vagrant/config/application.rb:1
/vagrant/Rakefile:4:in`require'
/vagrant/Rakefile:4
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in`load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:501:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:82:in`load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:81:in`load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:65:in `run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in`standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:63:in `run'
/usr/bin/rake:27

```
```

**Comment by chloerei** [comment]
因为中断了 rvm 的安装，所以 bundler 没装好

`gem install bundler`

中国特色网络问题经常导致 gem 下不了，最好全程翻墙。

**Comment by zuoyang** [comment]
这么惨烈的安装经历，学习了一把
